### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [sarahnade/project10#1]
Mostly looks very good! There are just a couple updates I'd like you to make:

There seems to be a styling issue that's putting any fields with validation errors out of alignment with the rest of the fields and also hiding the text of the error messages. Can you fix these?

Then I was also able to enter a negative number for the musicians, which is probably undesired. [This resource](https://www.google.com/search?q=rails+validate+greater+than+0) may help you resolve that. (And I'm really not trying to be cheeky linking to a set of Google results - just trying to help you learn what to search for!)

Let me know how that goes!

**Comment by sarahnade** [comment]
Thank you for pointing those out. Everything should be fixed now.

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
